{% set name = "amazon-sagemaker-sql-magic" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Uncomment the next line and remove the hard coded url in any releases above 0.1.3. We should follow the url pattern not the hardcoded link.
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f3120972c423bc2d1fd0c390c84e499435209e01115b2739c65912c4f4b82693 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy <2
    - pandas
    - ipython
    - sqlparse ==0.5.0
    - amazon-sagemaker-sql-execution >=0.0.7,<1

test:
  imports:
    - amazon_sagemaker_sql_magic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/amazon-sagemaker-sql-magic/
  summary: 'Package which provides sql magic commands for Sagemaker SQL extension'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kumarnzt
    - gogakoreli
    - varun196
    - HariniNarayanan
