{% set name = "amazon-sagemaker-sql-magic" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f9dc8f69104c910021ea99a506b813da6427d7afc2685a2a61ba3eab5204bf5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.8
    - pandas
    - ipython
    - sqlparse ==0.4.*
    - amazon-sagemaker-sql-execution >=0.0.7,<1

test:
  imports:
    - amazon_sagemaker_sql_magic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/amazon-sagemaker-sql-magic/
  summary: 'Package which provides sql magic commands for Sagemaker SQL extension'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kumarnzt
    - gogakoreli
    - varun196
    - HariniNarayanan
